### ISSUE TITLE
Green Fingers – Our first two UC activity diagrams

### ISSUE THREAD

**Issue by DHBW-Malte** [DHBW-Malte/gardeningApp#28]
https://dhbw-malte.github.io/gardeningApp/2024/10/13/uc-activity-diagrams.html

**Comment by millisom** [comment]
Dear Green Fingers,
we really liked your blogpost. It’s all nice and clear.
In both of your Activity Diagrams the box “display an error message to the user” has not further activity. 
Nothing comes after it. 

The Activity Diagram “Delete Plant” is very full and a bit confusing to read.
Some values are not necessary (in our opinion): 
for example, if a process is sending data to another one, you added another box that it’s receiving data. 
The diagram could be clearer, but other than that, it’s very good. 
The mockups are very nice and you printed down every step of the way. 
Thank you for showing your progress. 
We are looking forward to see more. 
S and E from GluGuide

**Comment by yasipd** [comment]
Hi Team,
Great work on the first two activity diagrams! It's clear that a lot of thought went into designing these flows. However, I see a few areas where there might be room for improvement:

1.User Experience in Edge Cases: While both use cases address the typical user flow, it might be helpful to consider edge cases. For example, in the "Show Gardens" use case, how does the system handle situations where the user has no gardens created yet? Displaying a friendly message or providing guidance on how to start could enhance the user experience.
2.Error Handling and Feedback: In the "Delete Plant" use case, it's great that you include a confirmation step before deletion. However, what happens if there's an error during deletion (for example the plant's data fails to delete properly)? It might be worth specifying the error handling flow—how the system informs users and whether there's an option to retry.

overall great job ! The use cases are clearly documented.
keep up the good work.

from Hobby Devs Team.

**Comment by DHBW-Malte** [comment]
Thank you for your feedback Emili, Sanna & Yasi. We have adjusted our activity charts to make them easier to read and we have also added a flow for the error messages.

**Comment by GT-XVII** [comment]
I'm nit picking here but some of the text boxes in the Activity diagram could be made larger to fit all the text within. Other wise I think everything has been done to a very high standard and meets most, if not all requirements from Prof Berk for that weeks homework.
